// Importing global CSS styles
import './globals.css'

// Importing type Metadata from Next.js
import type { Metadata } from 'next'

// Importing Inter font from Google Fonts via Next.js
import { Inter } from 'next/font/google'

// Initializing Inter font with Latin subset
const inter = Inter({ subsets: ['latin'] })

// Metadata object for the page
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// RootLayout component defining basic HTML structure and applying Inter font to body
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
