import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog",
  // title: {
  //   absolute: "Blog"
  // }
  description: "Generated by Next",
};

export default function Blog() {
  return (
    //
    <div>Blog page</div>
  );
}
